name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
      - '!main'
      - '![0-9]+.[0-9]+'
  pull_request:
    types: [ closed ]
    branches:
      - 'main'
      - 'develop'
      - '[0-9]+.[0-9]+'

jobs:
  lint-js:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Configure npm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install Node dependencies
        run: npm ci

      - name: Detect coding standard violations
        run: npm run lint

  release:
    needs: [ lint-js ]
    if: ${{ github.event.pull_request.merged == true && github.ref != 'refs/heads/develop' }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get npm cache directory
        id: npm-cache
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: Configure npm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Install Node dependencies
        run: npm ci

      - name: Set the tag version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

      - name: Prepare Release
        id: prepare-release
        continue-on-error: true
        uses: ./
        with:
          baseRef: ${{ github.base_ref }}
          headRef: ${{ github.head_ref }}
          tagRef: ${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: actions/create-release@v1
        if: steps.prepare-release.outcome == 'success' && steps.prepare-release.conclusion == 'success'
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
          release_name: ${{ steps.package-version.outputs.current-version }}
          body: |
            ${{ steps.prepare-release.outputs.changelog }}
            ${{ steps.prepare-release.outputs.props }}
          prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
